baseURL = "https://mathdoggy.github.io"
title = "Mathrew ʕ•ᴥ•ʔ Xian Bear Blog"
author = "Mathrew Xian"
copyright = "Copyright © 2025, Mathrew Xian."
languageCode = "en-US"
enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[module]
  [[module.imports]]
     path = "github.com/janraasch/hugo-bearblog"
  [module.hugoVersion]
     extended = true
     
     
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  description = "Hugo + Bear = :heart:"
  favicon = "images/github.png"
  images = ["images/logo.png"]
  title = "Mathrew ʕ•ᴥ•ʔ Xian Bear"
  # hideMadeWithLine = true
  enablePostNavigator = true
  dateFormat = "2006-01-02"
  
[markup]
  [markup.highlight]
    style = 'friendly'
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
